#!/usr/bin/env zsh

echo -n "${c[green]}Operating System: ${c[cyan]}$(_tmux_uname)"

echo -ne "${c[green]}Kernel: ${c[cyan]}"
echo -e  "$(uname -rm) "

echo -e "${c[green]}Hostname: ${c[cyan]}${HOST:-$HOSTNAME}"

echo -e "${c[green]}Ram Usages: ${c[cyan]}\n $(command free -h | grep -v +)"

echo -e "${c[green]}Disk Usages: ${c[cyan]}\n $(command df -h | sed -n '1 p') \n$(command df -h | grep '^/dev/*')"

echo -e "${c[green]}System Uptime: ${c[cyan]}$(_tmux_uptime)"

if [[ -f /var/log/auth.log ]]; then
  echo -e "${c[green]}Failed Login: ${c[cyan]}$(cat /var/log/auth.log 2>/dev/null | grep sshd | grep Fail | wc -l )"
else
  echo -e "${c[green]}Failed Login: ${c[cyan]}$( journalctl -u sshd 2>/dev/null | grep Fail | wc -l )"
fi

echo -en "${c[reset]}"
