#!/usr/bin/env bash


if check-if linux; then

  echo -ne "${c[green]}Operating System: ${c[cyan]}"
  echo -ne "$(uname -o) "
  echo -e "$(lsb_release -si -sr) "

  echo -ne "${c[green]}Kernel: ${c[cyan]}"
  echo -e  "$(uname -rm) "

  echo -e "${c[green]}Hostname: ${c[cyan]}${HOST:-$HOSTNAME}"

  echo -e "${c[green]}Ram Usages: ${c[cyan]}\n $(\free -h | grep -v +)"

  echo -e "${c[green]}Disk Usages: ${c[cyan]}\n $(\df -h | sed -n '1 p') \n$(df -h | grep '^/dev/*')"

  echo -e "${c[green]}System Uptime: ${c[cyan]}$(uptime | xargs| sed -e 's/.*up\ \(.*\),\ [0-9]*\ .*/\1/g')"

  [[ -f /var/log/auth.log ]] && \
    echo -e "${c[green]}Failed Login: ${c[cyan]}$(cat /var/log/auth.log | grep sshd | grep Fail | wc -l )" || \
    echo -e "${c[green]}Failed Login: ${c[cyan]}$( journalctl -u sshd | grep Fail | wc -l )"

  echo -en "${c[reset]}"

fi

if check-if android; then

  echo -ne "${c[green]}Operating System: ${c[cyan]}"
  echo -n "$(uname -o) "

  echo -ne "${c[green]}Kernel: ${c[cyan]}"
  echo -ne  "$(uname -r) "
  echo -e  "$(uname -m) "

  echo -e "${c[green]}Hostname: ${c[cyan]}$(hostname)"

  echo -e "${c[green]}Ram Usages: ${c[cyan]}\n $(\free -m | grep -v +)"

  echo -e "${c[green]}Disk Usages: ${c[cyan]}\n $(\df -h | sed -n '1 p') \n$(\df -h | grep '^/dev/*')"

  echo -e "${c[green]}System Uptime: ${c[cyan]}$(uptime | xargs| sed -e 's/.*up\ \(.*\),\ [0-9]*\ .*/\1/g')"

  echo -en "${c[reset]}"

fi

if check-if bsd; then

  echo -ne "${c[green]}Operating System: ${c[cyan]}"
  echo -ne "$(uname -o) "
  echo -e "$(uname -r) "

  echo -ne "${c[green]}Kernel: ${c[cyan]}"
  echo -ne  "$(uname -r) "
  echo -e  "$(uname -m) "

  echo -e "${c[green]}Hostname: ${c[cyan]}$(hostname)"

  echo -e "${c[green]}Disk Usages: ${c[cyan]}\n $(\df -h | sed -n '1 p') \n$(df -h | grep '^/dev/*')"

  echo -e "${c[green]}System Uptime: ${c[cyan]}$(uptime | xargs| sed -e 's/.*up\ \(.*\),\ [0-9]*\ .*/\1/g')"

  echo -en "${c[reset]}"

fi
